###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "nombreGenero": "rock",
    "anioOrigen": 1960,
    "popularidad": "alta",
    "paisOrigen": "Inglaterra",
    "instrumento": "batería"

}

###
DELETE http://localhost:9000/api/3 HTTP/1.1

###
PUT http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "nombreGenero": "pop",
    "anioOrigen": 1955,
    "popularidad": "baja",
    "paisOrigen": "Inglaterra",
    "instrumento": "guitarra"

}

//-------------         ARTISTAS         ----------------------

###
GET http://localhost:9000/api/mostrarArtistas HTTP/1.1


###
POST http://localhost:9000/api/addArtist HTTP/1.1
Content-Type: application/json

{
    "nombre": "Harry Styles",
    "edad": 27,
    "nacionalidad": "británico",
    "retirado": "no",
    "voz": "soprano",
    "idgenero": 1

}

###
DELETE http://localhost:9000/api/delete/3 HTTP/1.1

###

PUT http://localhost:9000/api/update/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taylor Swift",
    "edad": 32,
    "nacionalidad": "estadounidense",
    "retirado": "si",
    "voz": "mezzosoprano",
    "idgenero": 1

}
